# This file compiled from .travis.yml.in

sudo: false

language: python

python:
  - "3.5.2"

cache:
  pip: true

install:
  # Install Python dependencies
  - python -m pip install --upgrade pip==9.0.1
  - python -m pip install -r requirements3.txt

  # Invoke will get our other dependencies
  - invoke dependencies_ensure

script:
  - nosetests tests.fast
  - nosetests
